### ISSUE TITLE
Document design pattern #1 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#185]
As a developer, I require reference documentation to implement a network security policy that accomplishes  the following: 
- [ ] pod-to-pod communication within an OpenShift project/namespace is explicitly permitted
- [ ] pod-egress-to-internet communication within an OpenShift project/namespace is explicitly permitted
- [ ] demonstration/validation/testing that the above policies are functional

Create design pattern documentation inclusive of the BCGov network policy custom resource.

**Comment by stewartshea** [comment]
Egress policy sample: 

```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: egress-internet
spec:
  description: |
    allow the devops-platform-security-demo-sprint2-project1 namespace to talk to the internet
    namespace.
  source:
    - - $namespace=devops-platform-security-demo-sprint2-project1
  destination:
    - - ext:network=any
```

Intra-namespace policy example: 
```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: intra-namespace-comms
spec:
  description: |
    allow the devops-platform-security-demo-sprint2-project1 namespace to talk to itself
  source:
    - - $namespace=devops-platform-security-demo-sprint2-project1
  destination:
    - - $namespace=devops-platform-security-demo-sprint2-project1
```


Egress for specific pods by label example;

```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: app-1-app-2-egress-internet-permit
spec:
  description: |
    allow app-1 and app-2 to talk to the internet
  source:
    - - app=app-1
    - - app=app-2
  destination:
    - - ext:network=any
```

Specific pod policy within namespace example; 
```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: app-1-db-1-permit
spec:
  description: |
    allow app-1 to db-1 comms
  source:
    - - app=app-1
  destination:
    - - app=db-1


```
