### ISSUE TITLE
Regular users cannot create networksecuritypolicy objects

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#272]
As a regular OpenShift user I should be able to create networksecuritypolicy objects. Currently this requires elevated permissions.

**Comment by stewartshea** [comment]
Screenshots of the issue: 
![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/cc1f4a3b-30d1-4600-a57f-7eb3648b9afd)

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/72a8cbd7-17b3-4cfd-9f25-dd54c0e279bb)



Reference: 
https://docs.openshift.com/container-platform/3.11/admin_guide/custom_resource_definitions.html#creating-aggregated-cluster-role-crd_admin-guide-custom-resources

**Comment by stewartshea** [comment]
Reference: 
https://docs.openshift.com/container-platform/3.11/admin_guide/custom_resource_definitions.html#creating-aggregated-cluster-role-crd_admin-guide-custom-resources

Created and applied this clusterrole: 
```
## Allow project admins/editors to manage networksecuritypolicy objects
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: aggregate-networksecuritypolicy-admin-edit 
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true" 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
rules:
- apiGroups: ["secops.pathfinder.gov.bc.ca"] 
  resources: ["networksecuritypolicies"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"] 
```

Tested successfully: 
```
[sheastewart@sheawei Downloads]$ oc apply -f ~/tmp/netpol.yml 
networksecuritypolicy.secops.pathfinder.gov.bc.ca/inter-namespace-comms created
[sheastewart@sheawei Downloads]$ 

```
