### ISSUE TITLE
Clean up networksecuritypolicy CRD 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#274]
The crd for networksecurity policy has a mixture of `secopspolicies` and `networksecuritypolicy` language which will likely be confusing. This particular CRD should be focused on networksecuritypolicy only.

**Comment by stewartshea** [comment]
@jleach I updated the CRD and will merge my changes in soon. Would like to know if you're ok with the CRD changes

**Comment by stewartshea** [comment]
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksecuritypolicies.secops.pathfinder.gov.bc.ca
spec:
  group: secops.pathfinder.gov.bc.ca
  names:
    kind: NetworkSecurityPolicy
    listKind: NetworkSecurityPolicyList
    plural: networksecuritypolicies
    singular: networksecuritypolicy
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
