### ISSUE TITLE
BCGov NetworkSecurityOperator doesn't accept tags with multiple colons

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#310]
Attempting to use a label like `@app:k8s:serviceaccountname=builder` inside of the policy can't be applied into openshift. 

Trying a policy like this: 

```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: allow-builds-internet-access
spec:
  description: |
    allow builds to talk to the internet
  source:
    - - @app:k8s:serviceaccountname=builder
  destination:
    - - ext:network=any
```

Produces this error with oc: 
```
error: error parsing egress-internet-builds.yml: error converting YAML to JSON: yaml: line 8: found character that cannot start any token

```

Trying to wrap the item in single quotes causes a playbook failure: 
```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: allow-builds-internet-access
spec:
  description: |
    allow builds to talk to the internet
  source:
    - - '@app:k8s:serviceaccountname=builder'
  destination:
    - - ext:network=any
```

```
[sheastewart@sheawei network-policy]$ oc describe networksecuritypolicy allow-builds-internet-access
Name:         allow-builds-internet-access
Namespace:    devex-von-tools
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"secops.pathfinder.gov.bc.ca/v1alpha1","kind":"NetworkSecurityPolicy","metadata":{"annotations":{},"name":"allow-builds-internet-access",...
API Version:  secops.pathfinder.gov.bc.ca/v1alpha1
Kind:         NetworkSecurityPolicy
Metadata:
  Creation Timestamp:  2019-09-27T18:49:18Z
  Finalizers:
    finalizer.secops.pathfinder.gov.bc.ca
  Generation:        7
  Resource Version:  385679717
  Self Link:         /apis/secops.pathfinder.gov.bc.ca/v1alpha1/namespaces/devex-von-tools/networksecuritypolicies/allow-builds-internet-access
  UID:               829abb1f-e157-11e9-a1a2-00505683c9cc
Spec:
  Description:  allow builds to talk to the internet

  Destination:
    [ext:network=any]
  Source:
    [@app:k8s:serviceaccountname=builder]
Status:
  Conditions:
    Last Transition Time:  2019-09-27T19:09:51Z
    Message:               Running reconciliation
    Reason:                Running
    Status:                False
    Type:                  Running
    Ansible Result:
      Changed:             3
      Completion:          2019-09-27T19:19:03.174255
      Failures:            1
      Ok:                  6
      Skipped:             0
    Last Transition Time:  2019-09-27T19:19:03Z
    Message:               non-zero return code
    Reason:                Failed
    Status:                True
    Type:                  Failure
Events:                    <none>

```

**Comment by mitovskaol** [comment]
@stewartshea can we close this one?

**Comment by tosazuwa** [comment]
@stewartshea , please update

**Comment by stewartshea** [comment]
This one is still an issue and should be prioritised.  @jleach do you want to have a look at this?

**Comment by jleach** [comment]
👍

Regards,

Jason Leach

**Comment by jleach** [comment]
Working on this one. Looking into where (JSON parsing) is breaking down and what we can do about it.

**Comment by jleach** [comment]
I created a PR with a fix for this. A string with multiple colons will need to be quoted to be valid YAML. Not sure if this is going to cause problems for people or not if they don't have some sort of YAML linter running. In any case - those be the rules.

**Comment by stewartshea** [comment]
I'm not seeing this as functional; 

- Test NSP: 

```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: colon-testing
spec:
  description: |
    test with an object such as a service account source
  source:
    - - "$namespace=ws-test"
      - "@app:k8s:serviceaccountname=builder"
    - - "$namespace=ws-test"
      - "@app:k8s:serviceaccountname=deployer"
  destination:
    - - "int:network=internal-cluster-api-endpoint"

```


- Error: 

```
TASK [Process j2 template] *****************************************************
task path: /opt/ansible/apo_import.yaml:20
ok: [localhost] => {"ansible_facts": {"tdata": "APIVersion: 1\nlabel: \"custom-netpol-58ab21b216ed\" \ndata:\n  networkaccesspolicies:\n  - name: custom-netpol-colon-testing\n    description: test with an object such as a service account source \n    action: Allow\n    propagate: true\n    logsEnabled: true\n    subject:\n    - - $namespace=/bcgov/platform-services/non-production/kamloops/lab/ocp311/ws-test\n      - @app:k8s:serviceaccountname=builder\n    - - $namespace=/bcgov/platform-services/non-production/kamloops/lab/ocp311/ws-test\n      - @app:k8s:serviceaccountname=deployer\n    object:\n    - - int:network=internal-cluster-api-endpoint\n    associatedTags:\n    - k8s-uuid=ea2f81f0-032d-11ea-84c3-00505683c9cc\n"}, "changed": false}

TASK [Create policy] ***********************************************************
task path: /opt/ansible/apo_import.yaml:23
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/apoctl", "api", "import", "--namespace", "/bcgov/platform-services/non-production/kamloops/lab/ocp311/ws-test", "-f", "-"], "delta": "0:00:01.669109", "end": "2019-11-09 20:17:24.168875", "msg": "non-zero return code", "rc": 1, "start": "2019-11-09 20:17:22.499766", "stderr": "", "stderr_lines": [], "stdout": "error: yaml: line 12: found character that cannot start any token", "stdout_lines": ["error: yaml: line 12: found character that cannot start any token"]}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1  

```

**Comment by stewartshea** [comment]
it's the `@` symbol that it's having issue with @jleach

**Comment by stewartshea** [comment]
So this works; 
```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: colon-testing
spec:
  description: |
    test with an object such as a service account source
  source:
    - - "$namespace=ws-test"
      - "'@app:k8s:serviceaccountname=builder'"
    - - "$namespace=ws-test"
      - "'@app:k8s:serviceaccountname=deployer'"
  destination:
    - - "int:network=internal-cluster-api-endpoint"
```
