### ISSUE TITLE
Document the internal api requirements for new projects

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#396]
A user with a new project noticed that the docs don't cover the internal API access requirements. An example is here: 

```
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: pods-to-api
spec:
  description: |
    allow pods to talk to the internal api 
  source:
    - - $namespace=apndkr-dev
  destination:
    - - int:network=internal-cluster-api-endpoint
```

The documentation that users are accessing is here: https://developer.gov.bc.ca/Information-and-Application-Security/Custom-Policy
