### ISSUE TITLE
Update samples for namespace to namespace comm in Developer Guide

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#412]
The policy must include all source and destinations in both directions as follows:
```
spec:
  description: |
    allow hak2zo-dev to talk to gl2uos-dev
  destination:
    - - $namespace=hak2zo-dev
    - - $namespace=gl2uos-dev
  source:
    - - $namespace=gl2uos-dev
    - - $namespace=hak2zo-dev
```
