### ISSUE TITLE
Add compliance tracking configuration to repositories

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#497]
As a member of platform-services, I would like help teams be in compliance with the STRA and PIA process by adding configuration to the repositories that indicate the state of these processes.

```yaml
name: compliance
description: |
  This document is used to track a projects PIA and STRA
  compliance.
spec:
  - name: PIA
    status: completed
    last-updated: "2019-11-22T00:03:52.138Z"
  - name: STRA
    status: in-progress
    last-updated: "2019-11-22T00:03:52.138Z"
```
