### ISSUE TITLE
Devhub Issue: OpenShift User Guide to Creating and Using a Sysdig Team for Monitoring [short description here]

### ISSUE THREAD

**Issue by michaelshire** [BCDevOps/platform-services#788]
> path: (do not delete) https://github.com/BCDevOps/platform-services/blob/master/monitoring/sysdig/docs/sysdigteam_user_guide.md
 > (do not delete) devhub page: /OpenShift-User-Guide-to-Creating-and-Using-a-Sysdig-Team-for-Monitoring#sample-sysdig-team-object

## Devhub Content Issue
Suggest to include the namespace in the sample yaml.

Current:
```
apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: 101ed4-sysdigteam
spec:
  team:
    description: The Sysdig Team for the Platform Services Documize
    users:
    - name: shelly.han@gov.bc.ca
      role: ROLE_TEAM_MANAGER
    - name: patrick.simonian@gov.bc.ca
      role: ROLE_TEAM_EDIT
    - name: billy.li@gov.bc.ca
      role: ROLE_TEAM_STANDARD
    - name: olena.mitovska@gov.bc.ca
      role: ROLE_TEAM_READ
```

Suggested:
```
apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: 101ed4-sysdigteam
  namespace: 101ed4-sysdigteam
spec:
  team:
    description: The Sysdig Team for the Platform Services Documize
    users:
    - name: shelly.han@gov.bc.ca
      role: ROLE_TEAM_MANAGER
    - name: patrick.simonian@gov.bc.ca
      role: ROLE_TEAM_EDIT
    - name: billy.li@gov.bc.ca
      role: ROLE_TEAM_STANDARD
    - name: olena.mitovska@gov.bc.ca
      role: ROLE_TEAM_READ
```
